# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

def local_ip
  orig = Socket.do_not_reverse_lookup
  Socket.do_not_reverse_lookup =true # turn off reverse DNS resolution temporarily
  UDPSocket.open do |s|
    s.connect '8.8.8.8', 1 #google
    s.addr.last
  end
ensure
  Socket.do_not_reverse_lookup = orig
end


Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "my-centos7-libvirt"
  config.vm.hostname =  Pathname.new(File.dirname(__FILE__)).basename

  proxy_ip = local_ip
  config.proxy.http     = "http://%s:3128/" % [proxy_ip]
  config.proxy.http     = ""
  #config.proxy.https    = "http://192.168.0.2:3128/"
  config.proxy.no_proxy = "localhost,127.0.0.1,.example.com,10.0.2.15/24,192.168.33.10/24"

  config.ssh.insert_key = false

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = "8"
    libvirt.memory = "4096"
    libvirt.volume_cache = "unsafe"
  end

  #config.vm.provision :shell, path: "bootstrap.sh"
end
